# This is a basic workflow to help you get started with Actions
name: branch-deploy

# Controls when the workflow will run
on:
  workflow_dispatch:
#  issue_comment:
#    types: [ created ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    outputs:
      status: ${{ steps.check_issue.outputs.ISSUES }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check issue list
        id: check_issue
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          issues=$(gh issue list -l deploy)
          echo ::set-output name=ISSUES::$issues
      - name: Dump result
        run: |
          echo '${{ toJSON(steps.check_issue) }}'
          echo '${{ steps.check_issue.outputs.ISSUES }}'
  deploy:
    needs: check
    if: needs.check.outputs.status == ''
    runs-on: ubuntu-latest
    steps:
#      - name: Slash Command Dispatch
#        uses: peter-evans/slash-command-dispatch@v3
#        with:
#          token: ${{ secrets.PAT }}
#          reactions: false
#          commands: branch-deploy
      - name: Create start comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: 1
          repository: T-Toshiya/deploy-management-test
          body: |
            @${{ github.actor }}
            Start branch-deploy.
      - name: Dump context
        run: echo '${{ toJSON(github) }}'
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"
      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
      - name: Create end comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: 16
          body: |
            @${{ github.actor }}
            [Command run output][1]

            [1]: ${{ steps.vars.outputs.run-url }}
