# This is a basic workflow to help you get started with Actions
name: branch-deploy

# Controls when the workflow will run
on:
  issue_comment:
    types: [ created ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          reactions: false
          commands: |
            dev-deploy
      - name: dump context
        run: echo '${{ toJSON(github) }}'
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: 16
          body: |
            @${{ github.actor }}
            Start manually deploy to dev-deploy.
