# This is a basic workflow to help you get started with Actions
name: dev-deploy

on:
  workflow_dispatch:
    inputs:
      is_main_branch:
        type: boolean
        description: Is main branch?
        required: true
        default: false

#  push:
#    branches:
#      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'main' }}
    steps:
        - run: echo 'main ブランチを選択してください'
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if branch is not main
        if: ${{ github.ref_name != 'main' }}
        run: exit 1
      - name: dump context
        run: echo '${{ toJSON(github) }}'