# This is a basic workflow to help you get started with Actions
name: dev-deploy

on:
  workflow_dispatch:
    inputs:
      dryrun:
        type: boolean
        description: Is main branch?
        required: true
        default: false

#  push:
#    branches:
#      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: dump context
        run: echo '${{ toJSON(github) }}'