# This is a basic workflow to help you get started with Actions
name: dev-deploy

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack of start rollback
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,ref,workflow,message
          author_name: ${{ github.actor }}
          text: |
            Start rollback to xxx.
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
      - name: Fail if branch is not main
        if: ${{ github.ref_name != 'main' }}
        run: |
          echo 'main ブランチを選択してください'
          exit 1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Notify slack of deployment result
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,ref,workflow,message,took
          author_name: ${{ github.actor }}
          text: |
            Rollback has ${{
              (job.status == 'success' && 'succeeded') ||
              (job.status == 'failure' && 'failed') ||
              'cancelled'
            }} to xxx.
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
