name: notification to slack

on:
  workflow_call:
    inputs:
      text:
        required: true
        type: string
      color:
        required: true
        type: string
      status:
        required: false
        type: string
    secrets:
      slack_webhook_url:
        required: true

jobs:
  notify_start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Post message to Slack with Payload path
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "${{ inputs.color }}", 
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "${{ inputs.text }}"
                      }
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*repo:*\n<${{ github.event.repository.url }}|${{ github.repository }}>"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*commit:*\n<${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*ref:*\n ${{ github.ref }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*workflow:*\n<${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"
                        }
                      ]
                    },
                    {
                      "type": "context",
                      "elements": [
                        {
                          "type": "mrkdwn",
                          "text": "*Actor*: ${{ github.actor }}"
                        },
                        {
                          "type": "image",
                          "image_url": "${{ github.event.sender.avatar_url }}",
                          "alt_text": "cute cat"
                        }
                      ]
                    },
                    {
                      "type": "divider"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK