# This is a basic workflow to help you get started with Actions
name: prd-deploy

# Controls when the workflow will run
on:
  push:
    tags:
      - '20*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: dump context
        run: echo '${{ toJSON(github) }}'
