# This is a basic workflow to help you get started with Actions
name: test

# Controls when the workflow will run
on:
  #  repository_dispatch:
  #    types: [hoge]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches:
      - "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify_start_reuse:
    uses: ./.github/workflows/start-notification.yml
    with:
      repository: ${{ github.repository }}
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
  notify_start:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Post message to Slack with Payload path
          uses: slackapi/slack-github-action@v1.19.0
          with:
            payload-file-path: ./.github/resources/payload-notification.json
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
#        - name: Post message to Slack with Payload path
#          uses: slackapi/slack-github-action@v1.19.0
#          with:
#            payload-file-path: ./.github/resources/payload-notification.json
#            payload: |
#              {
#                "attachments": [
#                  {
#                    "color": "#00FF00",
#                    "blocks": [
#                      {
#                        "type": "header",
#                        "text": {
#                          "type": "plain_text",
#                          "text": "Start manually deploy to test."
#                        }
#                      },
#                      {
#                        "type": "section",
#                        "fields": [
#                          {
#                            "type": "mrkdwn",
#                            "text": "*repo:*\n<${{ github.event.repository.url }}|${{ github.repository }}>"
#                          },
#                          {
#                            "type": "mrkdwn",
#                            "text": "*commit:*\n<${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>"
#                          },
#                          {
#                            "type": "mrkdwn",
#                            "text": "*ref:*\n ${{ github.ref }}"
#                          },
#                          {
#                            "type": "mrkdwn",
#                            "text": "*workflow:*\n<${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"
#                          }
#                        ]
#                      },
#                      {
#                        "type": "context",
#                        "elements": [
#                          {
#                            "type": "mrkdwn",
#                            "text": "*Actor*: ${{ github.actor }}"
#                          },
#                          {
#                            "type": "image",
#                            "image_url": "${{ github.event.sender.avatar_url }}",
#                            "alt_text": "cute cat"
#                          }
#                        ]
#                      },
#                      {
#                        "type": "divider"
#                      }
#                    ]
#                  }
#                ]
#              }
#          env:
#            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
