# This is a basic workflow to help you get started with Actions
name: test

# Controls when the workflow will run
on:
  #  repository_dispatch:
  #    types: [hoge]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches:
      - "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify_start:
    uses: ./.github/workflows/notification.yml
    with:
      notification_text: "Start manually deploy to ${{ github.repository }}."
      notification_color: "#0953FF"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
  notify_end:
    needs: notify_start
    uses: ./.github/workflows/notification.yml
    with:
      notification_text: "Deployment has succeeded to ${{ github.repository }}."
      notification_color: "#00FF00"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
