# This is a basic workflow to help you get started with Actions
name: test

# Controls when the workflow will run
on:
  #  repository_dispatch:
  #    types: [hoge]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches:
      - "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify_start:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - run: echo "${{ github.event_name }}"
        - name: Post message to Slack with Payload path
          id: slackPayloadFile
          uses: ./
          with:
            payload-file-path: ./.github/resources/payload-notification.json
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Send GitHub trigger payload to Slack Workflow Builder
#        id: slack
#        uses: slackapi/slack-github-action@v1.19.0
#        with:
#          payload-file-path: ./.github/resources/payload-notification.json
##          payload: |
##            {
##              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
##              "blocks": [
##                {
##                  "type": "section",
##                  "text": {
##                    "type": "mrkdwn",
##                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
##                  }
##                }
##              ]
##            }
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
