# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [hoge]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify_start:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack of start manually deployment
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,ref,workflow,message
          author_name: ${{ github.actor }}
          mention: ${{ github.event.client_payload.mention }}
          text: |
            Start manually deploy to test.
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  notify_end:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Notify slack of deployment result
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          fields: repo,commit,ref,workflow,message
          author_name: ${{ github.actor }}
          text: |
            Deployment has ${{
              (env.WORKFLOW_CONCLUSION == 'success' && 'succeeded') ||
              (env.WORKFLOW_CONCLUSION == 'failure' && 'failed') ||
              'cancelled'
            }} to test.
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
