name: test

on:
  workflow_dispatch:

  push:
    branches:
      - "*"

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: dump context
        run: echo '${{ job.status }}'
  notify_start:
    uses: ./.github/workflows/notification.yml
    with:
      text: "Start manually deploy to dev-repository."
      color: "#0953FF"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
  notify_end:
    needs: notify_start
    uses: ./.github/workflows/notification.yml
    with:
      text: "Deployment has succeeded to dev-repository."
      color: "#00FF00"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
